### ISSUE TITLE
Joystick controls are wrong

### ISSUE THREAD

**Issue by Iva2n** [Vespa-Robotics-7603/VespaRobotics2024-25#6]
Right goes backwards, left goes forwards.

Its not supposed to do that.

**Comment by Broclly** [comment]
update: 

it should be noted that newer code adds a slight fix; forward and backward now officially move their counter parts (verified needed)

**Comment by Broclly** [comment]
@Iva2n please add more information at what went wrong, so we can debug.

**Comment by litszwaiboris** [comment]
Note: @Iva2n stated that it is for the previous version of the robot's code, the problem might have been fixed already.

**Comment by yippii** [comment]
Note: @Iva2n stated that it is for the previous version of the robot's code, the problem might have been fixed already.

**Comment by yippii** [comment]
Going to check on main before reopening the issue.

**Comment by yippii** [comment]
Resolved and closed indefinitely.
